### ISSUE TITLE
[Feature Request] Visually Merge identical entities of the same type

### ISSUE THREAD

**Issue by cplir-c** [Discusser/TooManyEntities#1]
With your pit of 700 cows, this would look like a suuuper wide cow (50x1.6x50 blocks or something).

I realize this would probably require some kind of entity rendering mixin, in order to only scale them on two axes.

As a side effect, two cows in a boat together might look like an extra long cow.

**Comment by Discusser** [comment]
This is outside of the scope of this mod. This mod is only intended as a performance mod
