### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by zenithBemusement** [Discusser/TooManyEntities#2]
Mod Version: 1.0.1
Minecraft Version: 1.20.1
Neoforge Version: 47.1.106

Critical error on start up:

> Too Many Entities (too_many_entities) encountered an error during the sided_setup event phase:
> java.lang.NoSuchMethodError: 'void net.minecraftforge.common.MinecraftForge.registerConfigScreen(java.util.function.Function)'

Full crash log:
[crash-2024-08-20_04.05.12-fml.txt](https://github.com/user-attachments/files/16673209/crash-2024-08-20_04.05.12-fml.txt)

**Comment by Discusser** [comment]
You are using NeoForge with a Forge mod. On 1.20.1, it is recommended to not use NeoForge, or if you do, exclusively use mods that are compatible with NeoForge, otherwise just use Forge.
For versions past 1.20.1, I will port the mod to NeoForge, but everything before that will remain on Forge.

**Comment by zenithBemusement** [comment]
Oh I didn't even notice, huh. 9 times outta 10 they're cross-compatible, so I didn't really think to check. Mea culpa!
